### ISSUE TITLE
Integrate SingleFile as a Better Snapshot Option

### ISSUE THREAD

**Issue by louy2** [zotero/translators#2217] opened 2020-07-25 03:18 UTC
I use Zotero to save a lot of webpages. The snapshot from Zotero has always been kinda lackluster at actually preserving the content and look of the pages. It can lose lazily loaded images, which are very common on big platforms such as Medium. It can also download way more than I intend to, such as embedded videos on media.ccc.de, and not even able to play the video back in the snapshot because of path mismatch issues. 

I have been using another extension called [SingleFile](https://github.com/gildas-lormeau/SingleFile) to take snapshots for a while. It preserves lazily loaded images, while only taking the preview frame of an embedded video. I have been doing this manually, but I wonder if there is a way to integrate it with Zotero, either by collaborating with it as a peer dependency, or incorporating its algorithm. From the same author there is also [SingleFileZ](https://github.com/gildas-lormeau/SingleFileZ), which utilizes the ZIP file format to avoid encoding everything into one HTML, which if unzipped is quite close to the current snapshot model but with better results.

**Comment by dstillman** [comment] 2020-07-25 04:02
We're actually working on this at the moment. We're going to be using a modified version of SingleFileZ to save a ZIP (not its custom HTML+JS+ZIP format, but just the SingleFileZ folder structure in a regular ZIP file that's displayed via Zotero and unzippable outside for future-proofing).

Duplicate of https://github.com/zotero/zotero-connectors/pull/319

**Closed by dstillman** 2020-07-25 04:02 UTC
