### ISSUE TITLE
WHO document translator request

### ISSUE THREAD

**Issue by mvolz** [zotero/translators#1544] opened 2018-02-03 08:51 UTC
i.e. http://apps.who.int/iris/handle/10665/70863

Has relatively good metadata in it so I would think the embedded metadata translator would be a good start.

**Comment by adam3smith** [comment] 2018-02-03 19:29
yeah, definitely seems worthwhile + quick

**Comment by zuphilip** [comment] 2018-03-11 08:27
Duplicate of #791

**Comment by zuphilip** [comment] 2018-09-02 17:11
This is now implemented.

**Closed by zuphilip** 2018-09-02 17:11 UTC
Labels: Difficulty: Easy, New Translator, Workshop
