### ISSUE TITLE
Twitter translator doesn't work on first load

### ISSUE THREAD

**Issue by rmzelle** [zotero/translators#2750] opened 2021-11-18 16:05 UTC
I often open Twitter links from Gmail emails into new Firefox tabs ("Open Link in New Tab"). For several weeks/months now, invariably the Twitter translator fails when the page loads in a non-active tab:

![image](https://user-images.githubusercontent.com/77951/142450555-c4798308-5e93-4b3f-9336-12f6fef9c761.png)

The Twitter translator works after reloading the page, or if I quickly switch to the newly opened tab well before the page finishes loading:

![image](https://user-images.githubusercontent.com/77951/142450733-964ef9c4-6e77-44af-8dff-ec7cf826114d.png)

P.S. this also happens in Chrome for me, although the "quickly-switch-to-the-new-tab" trick doesn't work for me there.

**Comment by AbeJellinek** [comment] 2021-11-18 22:54
Ack.

This issue was originally introduced in c5e03788f76570ea853a8d2d751754ea7ca4315a, which narrowed detection to eliminate a translation error on full-screen media pages that we have no way to scrape. 971a137c022d2e7fd7fb2adf24fb3cf5ae878305 reverted those changes because of the issue you're seeing, and 16d27b57cba95a386c62a92d8053970f9199c126 was intended to restore the narrower detection with the addition of a call to `monitorDOMChanges` to rerun detection when the page title changes.

I've just pushed a fix reverting the regex check. Occasional errors when translating media pages are better than frequent missed detections.

**Closed** 2021-11-18 22:53 UTC

**Comment by rmzelle** [comment] 2021-11-20 21:48
Still running into this issue (e.g. with https://twitter.com/pronklotte/status/1461363683636830225?s=27 ), even after using the "Update Now" button to update my translators.

**Comment by AbeJellinek** [comment] 2021-11-21 03:17
Odd. `detectWeb` only looks at the URL now; a page like that should work fine. Could you give me a connector debug ID?

**Comment by rmzelle** [comment] 2021-11-21 04:58
Sorry for the false alarm. It seems to work now. Thanks for the quick fix!
