### ISSUE TITLE
ResearchGate.net (new translator request)

### ISSUE THREAD

**Issue by mvolz** [zotero/translators#1426] opened 2017-09-29 10:07 UTC
Research gate seems to be archiving a lot of papers. Example: https://www.researchgate.net/publication/238084600_Global_burden_of_obstructed_labour_in_the_year_2000

**Comment by dstillman** [comment] 2017-09-29 10:20
Though not super well, at least for that example — the BibTeX has the wrong year and incorrect capitalization of one of the author's names, and no mention of the WHO:

```
@article{article,
author = {Dolea, Carmen and Abouzahr, Carla},
year = {2000},
month = {01},
pages = {},
title = {Global burden of obstructed labour in the year 2000},
booktitle = {Evidence and Information for Policy}
}
```

Google Scholar doesn't include the department (EIP) but does get the rest right:

```
@article{dolea2003global,
  title={Global burden of obstructed labour in the year 2000},
  author={Dolea, Carmen and AbouZahr, Carla},
  journal={World Health Organization},
  year={2003}
}
```

PDF is here: http://www.who.int/healthinfo/statistics/bod_obstructedlabour.pdf

**Comment by mvolz** [comment] 2017-09-29 10:36
Yeah, that one's tricky. I've just come across it a lot in the last couple of days for other papers as well though, like here's a book chapter: https://www.researchgate.net/publication/221916192_Sexual_Assault_in_Childhood_and_Adolescence

**Comment by zuphilip** [comment] 2017-09-29 12:31
This looks like a duplicate of #1398 which was realized in #1399. The research translator works for me in both examples (also metadata in RG is wrong and poor). No?

**Comment by mvolz** [comment] 2017-09-29 12:54
Whoops. :) Sorry!

**Closed** 2017-09-29 12:55 UTC
