### ISSUE TITLE
Regexp for Aleph translator

### ISSUE THREAD

**Issue by zuphilip** [zotero/translators#926] opened 2015-08-01 13:40 UTC
There are still some missing cases in the regexp for the Aleph translator, see e.g. NDL https://forums.zotero.org/discussion/20128/ndl-import/#Comment_230187 The problem is a backslash: `https://ndlopac.ndl.go.jp/F`<b>/</b>`?func=find` . Thus we can fix this by changing the regexp to
```
^https?://[^/]+/F(/[A-Z0-9\-]+(\?.*)?$|/?\?func=find|\?func=scan|\?func=short)
```
Or are there better ways to fix this?

**Comment by adam3smith** [comment] 2015-08-01 13:47
the way I see this, the problem is that there's nothing between ```/F/``` and ```?func``` -- easy to fix the regex simply by replacing ```[A-Z0-9\-]+``` with ```[A-Z0-9\-]*```
also needs to be done in a couple of spaces in the translator. I can do that. Let me know if I'm overlooking something.

**Comment by zuphilip** [comment] 2015-08-01 13:59
You are right, that looks better to change. There might be more "false-positives" with the `*`, but IMO this is negligable. That would be good if you can make the changes.

**Comment by adam3smith** [comment] 2015-08-01 18:40
fixed in https://github.com/zotero/translators/commit/39d5bfe4a931224c60f6087411c7ba971cc448a5

**Closed** 2015-08-01 19:00 UTC
