### ISSUE TITLE
OpenGraph video metadata not working

### ISSUE THREAD

**Issue by QbDesu** [zotero/translators#2047] opened 2019-11-04 15:21 UTC
Because of an [issue on another project](https://github.com/voc/voctoweb/issues/387) I found that Zotero doesn't support importing OpenGraph video metadata. So I tested wether articles were supported or not and it turns out they are. So I dug around in the translator code base to find the following:

https://github.com/zotero/translators/blob/2901ba9fa5b4158cf87697a979a55ee7ad867fef/RDF.js#L55-L77

As you can see, the OpenGraph namespace `og` as well as the `article` and `book` subnamespace are in the namespace object n but no `video` or `music`  subnamespace.

https://github.com/zotero/translators/blob/2901ba9fa5b4158cf87697a979a55ee7ad867fef/RDF.js#L1080-L1098

But in the code there are also references to `n.video` and `n.music`, which were probably intended to hold the respective OpenGraph subnamespaces. At least `release_date` would the right attribute. But as far as I can tell they aren't defined anywhere.

I could open a PR if you like or you can add it yourself I don't really care either way. But I'm holding off on opening a PR because I can't tell for sure if it's actually what is causing the problem or if it's unrelated because I literally just dug around the code base for 10 minutes to find this.

**Comment by zuphilip** [comment] 2019-11-05 07:27
These lines come from the following commit https://github.com/zotero/translators/commit/3c3b78cb5d1d56e72c47d143a1d708b60ef2e0a4 by @adam3smith some years ago. And, yes, I agree with you. It looks like the two lines for the two subnamespaces where added in Embedded Metadata translator instead of RDF translator.

Go ahead with a PR and I am happy to look at it! Also some test data would be good to prevent this in the future.

**Comment by Necr0** [comment] 2019-12-20 11:34
From what I could tell the root of the problem is something else which I could not fix because I'm having a very hard time wrapping my head around the translator code, sorry. It would probably be for the best if somebody else who understands it looks into it and fixes it.

**Comment by zuphilip** [comment] 2019-12-21 19:21
Okay, PR #2094 will fix this.

**Comment by eest9** [comment] 2020-10-29 01:27
Is there any reason why this Pull Request #2094 was never merged? :thinking:

**Closed** 2021-06-17 20:34 UTC
